services:
  - type: web
    name: scraper-backend
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.app.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PORT
        value: 8000
    plan: free
    region: virginia

  - type: web
    name: scraper-worker
    runtime: node
    rootDir: scraper
    buildCommand: |
      npm install
      npx @puppeteer/browsers install chrome stable
    startCommand: node src/scraper.js
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "false"
    plan: free
    region: virginia
